Tap
CadeiraCuidadora/relatorio pull request #18
Opened 2017-03-28 23:32 UTC by TiagoAssuncao

2017-03-28 23:48 UTC, wiltonsr commented on editaveis/tap.tex
> +Tendo em vista as limitações de prazo, dinheiro e infraestrutura dos
trocaria dinheiro pro 'orçamento'

2017-03-28 23:48 UTC, wiltonsr commented on editaveis/tap.tex
> +modelo 5W2H, que está descrito a seguir:
seria bom dar uma breve descrição do que é o 5w2h e uma referência tbm serai legal

2017-03-28 23:48 UTC, wiltonsr commented on editaveis/tap.tex
> +    \item \textbf{What:} Sitema integrado com subsistemas de movimentação,
Sistema está escrito errado, tá 'sitema'

2017-03-28 23:48 UTC, wiltonsr commented on editaveis/tap.tex
> +O projeto tem como objetivo oferecer à pessoas indivíduo com mobilidade reduzida
pessoas ou individuos? ficou meio confuso

2017-03-28 23:48 UTC, wiltonsr commented on editaveis/tap.tex
> +próximos e médicos ou enfermeiros contratados, seriam notificados, com atraso
ficou confusa a parte do atraso, acho que faltou especificar o valor do atraso

2017-03-28 23:48 UTC, wiltonsr commented on editaveis/tap.tex
> +        Plano de ação: Ajustas datas de cronograma de forma a acelerar prazos atrasados
'Ajuste'

2017-03-28 23:48 UTC, wiltonsr commented on editaveis/tap.tex
> +        Plano de ação: Repensar o escopo do projeto afim de adapá-lo aos novos requisitos
'adaptá-lo'

2017-03-28 23:51 UTC, TiagoAssuncao commented on editaveis/tap.tex
> +modelo 5W2H, que está descrito a seguir:
Será que vem ao caso mesmo?

2017-03-28 23:59 UTC, DylanGuedes requested changes

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +Tendo em vista as limitações de prazo, dinheiro e infraestrutura dos
achei essa frase um pouco solta. Sugestão: conectar com a anterior, ou cortar ela mesmo.

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +    através de um aplicativo nativo android e de uma plataforma web.
talvez fosse melhor não falar que é android (pra omitir a tecnologia, deixando mais alto nível).

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +    \item \textbf{Who:} Alunos dos cursos de Engenharias do Campus UnB Gama, nos
o "nos quais" soou estranho. Sugestão: "... UnB Gama, que cursam a disciplina de Projeto Integrador 2".

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +O projeto tem como objetivo oferecer à pessoas indivíduo com mobilidade reduzida
O início soou estranho. Sugestão: "O projeto tem como objetivo oferecer à familiares de pacientes com mobilidade reduzida uma cadeira de rodas motorizada, com fácil..."

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +e que tenha total controle sobre os sinais vitais do paciente, a fim de avaliar
Essa parte soou estranha, porque a cadeira de rodas não controla os sinais vitais do paciente, só monitora.

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +as condições do mesmo e julgar se ele está em estado normal de saúde ou corre
Sugestão:
"a fim de avaliar suas condições de saúde e julgar se seu estado pode ser considerado normal".

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +um mínimo, do seu estado através de um site e um aplicativo.
"com atraso um mínimo" soou estranho.

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +são muito caras no mercado atual, além de que não existe nenhuma que possui
Trocar 'possui' por 'possua'

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +são muito caras no mercado atual, além de que não existe nenhuma que possui
Eu também trocaria "além de que não existe nenhuma" por "não existindo nenhuma que possua.."

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +um sistema de monitoramento da saúde do paciente, dificultando, então, seu
Eu acho que essa parte do "dificultando um resgate" pode ser cortada.

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +preocupação e tempo, a vida dos cuidadores, uma vez que não será mais necessária
acho que não precisa das virgulas. Sugestão:
"O que facilita em termos de preocupação e tempo a vida dos cuidadores, uma vez que.."

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +As restruções do projeto UMISS são as descritas as seguir:
misstype: "restruções"

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +    \item Limitação de custos do projeto, calibrado pela quantidade que o grupo estará disposta a colaborar;
Eu trocaria "pela quantidade" por "pelo montante", que parece ser um jeito melhor de expressar quantia de dinheiro.

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +Os principais riscos presentes na execução do Projeto UMISS, bem como suas medidas preventivas, estão explícitas a seguir:
acho que o correto seria "explicitadas", não "explícitas".

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +Plano de ação: Obter feedbacks dos membros sobre a atuação e gerar planos de
Usa itálico em 'feedback', e não precisa botar no plural. Sugestão: 'feedback'.

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +        Plano de ação: Repensar o escopo do projeto afim de adapá-lo aos novos requisitos
Misstype: "adaptá-lo"

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +engenharia de software. Sendo assim se multiplicarmos os 10 integrantes pelo
põe "Engenharia de Software" capitalizado (primeira letra maiúscula)

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +engenharia de software. Sendo assim se multiplicarmos os 10 integrantes pelo
Depois do "sendo assim", usa vírgula:
"Sendo assim, se multiplicarmos..."

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +Professores da matéria Projeto Integrador 2 do primeiro semestre de 2017 que
depois de 2017 tem virgula:
"... do primeiro semestre de 2017, que..."

2017-03-28 23:59 UTC, DylanGuedes commented on editaveis/tap.tex
> +As entregas do produto serão feitas em três partes, dividos em pontos de controle
acho que seria "divididas", pra concordar com a palavra "entrega"

2017-03-29 00:21 UTC, TiagoAssuncao commented on editaveis/tap.tex
> +um mínimo, do seu estado através de um site e um aplicativo.
#fixed

2017-03-29 00:27 UTC, TiagoAssuncao commented on editaveis/tap.tex
> +        Plano de ação: Repensar o escopo do projeto afim de adapá-lo aos novos requisitos
#fixed

2017-03-29 00:33 UTC, DylanGuedes approved these changes

2017-03-30 00:29 UTC, merged